/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "ERC20Detailed"): TruffleContracts.ERC20DetailedContract;
      require(name: "ERC20Pausable"): TruffleContracts.ERC20PausableContract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "MESGToken"): TruffleContracts.MESGTokenContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "Pausable"): TruffleContracts.PausableContract;
      require(name: "PauserRole"): TruffleContracts.PauserRoleContract;
    }
  }
}
